### ISSUE TITLE
新的问题：无法对多个内含不同解压密码压缩包的文件夹进行解压。

### ISSUE THREAD

**Issue by FrostNova67204** [Mario-Hero/toolUnRar#1]
操作场景：有数个文件夹，每个文件夹内都有一个压缩包及其压缩密码，格式为XXXXX.zip及password.txt，txt内部除密码外没有其他内容，每个txt内的密码都不一样。
问题：当把这些文件夹选中、同时拖进.py脚本时，只有第一个文件夹内的压缩包会被正确地以其所在的txt中的密码进行解压，其余文件夹内的压缩包都会报错。
当一个一个地拖入脚本进行解压时不会出现这个问题。

**Comment by Mario-Hero** [comment]
我刚刚上传了新版本，应该已经解决了，看一下。

**Comment by FrostNova67204** [comment]
经测试，问题已经解决。感谢大大❤

**Comment by Mario-Hero** [comment]
> 经测试，问题已经解决。感谢大大❤

问题解决
