### ISSUE TITLE
ERROR: Can't load module: 7z.dll ，密码已填写但无法解压，不使用脚本可直接解压

### ISSUE THREAD

**Issue by specked2527** [Mario-Hero/toolUnRar#4]
是打包下载项目的
‘密码’ “密码”  单双引号设置无效
![捕获](https://github.com/Mario-Hero/toolUnRar/assets/124735279/05fbe973-c61a-4582-b651-ff56417ff72d)

**Comment by Mario-Hero** [comment]
我改了一下，你再重新下载试一下

**Comment by specked2527** [comment]
> 我改了一下，你再重新下载试一下

非常有趣

![捕获](https://github.com/Mario-Hero/toolUnRar/assets/124735279/36a2a420-98b8-40a0-ac13-1f543472743f)

**Comment by Mario-Hero** [comment]
放英文路径里运行试一下？
你可以自己[下载](https://7-zip.org/)一个7z安装，就不用我这个包里的7z了

**Comment by specked2527** [comment]
> 放英文路径里运行试一下？ 你可以自己[下载](https://7-zip.org/)一个7z安装，就不用我这个包里的7z了

哦，我一开始就已经装了7z uwp版
我用位置里的两文件 7z.dll | 7z.exe
替换后可以了  C:\Program Files\WindowsApps\HaukeGtze.7-ZipFileManagerUnofficial_1.2201.1.0_x64__6bk20wvc8rfx2

新问题：即使通过脚本解压了，但还是说我No passsword，还有这个'C:\Program'是什么东西
`Please install chardet
'C:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'C:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'C:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'.' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'C:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'C:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'C:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'.' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
该版本的 Z:\·Data 4T\百度网盘 666GB\toolUnRar-main\7z.exe 与你运行的 Windows 版本不兼 容。请查看计算机的系统信息，然后联系软件发布者。
Finish.
No passsword for: yo优优mi密码moxing.zip`
![捕获](https://github.com/Mario-Hero/toolUnRar/assets/124735279/818dfde0-d3e8-45b9-9e6a-dd80d5663810)

**Comment by Mario-Hero** [comment]
一般情况下是不会有这个问题的，其实就是我访问C:\Program Files里的解压程序时，系统把中间的空格误认为了路径要分割，所以就只读了前面一部分C:\Program，导致找不到路径。不过没关系，这个包里的7z.exe和UnRAR.exe解压程序也能用。
至于no password for 一般是找不到密码会这样，或者压缩包有损坏。
另外说一句，你这个资源我也下过。。。

**Comment by specked2527** [comment]
没关系，能运行就好。（那我就不客气了，网盘里有一堆不知到是怎么来的压缩包，并且我不知道密码，唯一知道的只有3个密码。
现在有两选择，

1. 全部删除
2. 用已知的3个密码，一个一个试出来

这个脚本真的很好用。




![捕获](https://github.com/Mario-Hero/toolUnRar/assets/124735279/f9a4a72f-1ae5-427d-ba2a-377b7cc68374)


> 一般情况下是不会有这个问题的，其实就是我访问C:\Program Files里的解压程序时，系统把中间的空格误认为了路径要分割，所以就只读了前面一部分C:\Program，导致找不到路径。不过没关系，这个包里的7z.exe和UnRAR.exe解压程序也能用。 至于no password for 一般是找不到密码会这样，或者压缩包有损坏。 另外说一句，你这个资源我也下过。。。
